name: Run Selenium Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Mock API Server
        run: |
          nohup python mock_api.py > mock_api.log 2>&1 &
          sleep 5  # Give server time to start
        shell: bash

      - name: Run tests
        run: pytest -m "api or login" --browser ${{ matrix.browser }} --alluredir=allure-results
