name: Run Selenium Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Mock API Server
        run: |
          nohup python api/mock_api.py > mock_api.log 2>&1 &

          # Wait for the API to become available (max 30 seconds)
          for i in {1..30}; do
            if curl --silent --fail http://localhost:5000/health; then
              echo "Mock API is up!"
              break
            fi
            echo "Waiting for Mock API to start..."
            sleep 1
          done
        shell: bash

      - name: Run tests
        run: pytest -m "api or login" --browser ${{ matrix.browser }} --alluredir=allure-results
        env:
          API_HOST: localhost
